import { jsPDF } from 'jspdf';
import type { Inspection } from '../../types';

export function generateInspectionReport(inspection: Inspection, inspectorName?: string): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('PackCheck — Inspection Report', pageWidth / 2, y, { align: 'center' });
  y += 6;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Legal Metrology (Packaged Commodities) Compliance Verification', pageWidth / 2, y, { align: 'center' });
  y += 10;

  // Horizontal divider
  doc.setLineWidth(0.5);
  doc.line(20, y, pageWidth - 20, y);
  y += 10;

  // Inspection Metadata
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Inspection Details', 20, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Inspection ID: ${inspection.id}`, 20, y); y += 6;
  doc.text(`Date & Time: ${new Date(inspection.inspection_date).toLocaleString('en-IN')}`, 20, y); y += 6;
  doc.text(`Inspector Name: ${inspectorName || 'Inspector'}`, 20, y); y += 6;
  doc.text(`Product Name: ${inspection.product_name || 'Unspecified Product'}`, 20, y); y += 6;
  doc.text(`Category: ${inspection.category || 'General'}`, 20, y); y += 12;

  // Compliance Summary
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Compliance Summary', 20, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Compliance Score: ${inspection.compliance_score || 0}%`, 20, y); y += 6;
  doc.text(`Overall Status: ${(inspection.overall_result || 'Pending').toUpperCase().replace('_', ' ')}`, 20, y); y += 6;
  doc.text(`Rules Checked: ${inspection.total_rules_checked || 0}`, 20, y); y += 6;
  doc.text(`Passed: ${inspection.rules_passed || 0}`, 20, y); y += 6;
  doc.text(`Requires Review: ${inspection.rules_review || 0}`, 20, y); y += 6;
  doc.text(`Issues Identified: ${inspection.rules_failed || 0}`, 20, y); y += 12;

  // Declarations Table
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Declaration Verification Results', 20, y);
  y += 8;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Rule / Field', 20, y);
  doc.text('Detected Value', 85, y);
  doc.text('Status', 160, y);
  y += 4;

  doc.setLineWidth(0.2);
  doc.line(20, y, pageWidth - 20, y);
  y += 6;

  doc.setFont('helvetica', 'normal');
  const results = inspection.rule_results || [];
  results.forEach((res) => {
    if (y > 260) {
      doc.addPage();
      y = 20;
    }
    const valText = res.detectedValue || 'Not detected';
    const statusLabel = res.status === 'pass' ? '✓ Verified' : res.status === 'review' ? '⚠ Review' : '✗ Issue';
    
    doc.text(res.ruleName.substring(0, 32), 20, y);
    doc.text(valText.substring(0, 42), 85, y);
    doc.text(statusLabel, 160, y);
    y += 7;
  });

  y += 10;
  if (y > 240) {
    doc.addPage();
    y = 20;
  }

  // Legal Disclaimer Footer
  doc.setLineWidth(0.5);
  doc.line(20, y, pageWidth - 20, y);
  y += 8;

  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.text(
    'This report is generated to assist in package inspection and is intended as a preliminary assessment.',
    20, y
  );
  y += 5;
  doc.text(
    'Findings should be manually verified by a qualified inspector before any enforcement action. Does not constitute a final legal judgment.',
    20, y
  );
  y += 8;
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated by PackCheck — ${new Date().toISOString()}`, 20, y);

  return doc;
}
