import type { Rule } from '../../types';

export const DEFAULT_RULES: Rule[] = [
  {
    id: 'LM-PC-001',
    field: 'manufacturer',
    name: 'Manufacturer Details',
    description: 'Name and complete address of the manufacturer or packer must be declared on the package.',
    reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 — Rule 6(1)(a)',
    checkType: 'presence',
    severity: 'high',
    applicableTo: ['all'],
    isActive: true,
  },
  {
    id: 'LM-PC-002',
    field: 'genericName',
    name: 'Common / Generic Name',
    description: 'Common or generic name of the commodity contained in the package must be declared.',
    reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 — Rule 6(1)(b)',
    checkType: 'presence',
    severity: 'high',
    applicableTo: ['all'],
    isActive: true,
  },
  {
    id: 'LM-PC-003',
    field: 'netQuantity',
    name: 'Net Quantity',
    description: 'Net quantity in terms of standard unit of weight or measure or number must be declared.',
    reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 — Rule 6(1)(c)',
    checkType: 'presence',
    severity: 'high',
    applicableTo: ['all'],
    isActive: true,
  },
  {
    id: 'LM-PC-004',
    field: 'mrp',
    name: 'Maximum Retail Price (MRP)',
    description: 'Maximum Retail Price inclusive of all taxes must be declared clearly on the package.',
    reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 — Rule 6(1)(e)',
    checkType: 'presence',
    severity: 'high',
    applicableTo: ['all'],
    isActive: true,
  },
  {
    id: 'LM-PC-005',
    field: 'manufacturingDate',
    name: 'Date of Manufacture / Packing',
    description: 'Month and year in which the commodity is manufactured, packed, or imported must be stated.',
    reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 — Rule 6(1)(d)',
    checkType: 'presence',
    severity: 'high',
    applicableTo: ['all'],
    isActive: true,
  },
  {
    id: 'LM-PC-006',
    field: 'bestBefore',
    name: 'Best Before / Expiry Date',
    description: 'Expiry date or best before statement must be clearly declared for perishable commodities.',
    reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 — Rule 6(1)(d)',
    checkType: 'presence',
    severity: 'high',
    applicableTo: ['all'],
    isActive: true,
  },
  {
    id: 'LM-PC-007',
    field: 'consumerCare',
    name: 'Consumer Care Details',
    description: 'Name, address, telephone number, and email address of person/office to be contacted in case of consumer complaints.',
    reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 — Rule 6(1)(ac)',
    checkType: 'presence',
    severity: 'medium',
    applicableTo: ['all'],
    isActive: true,
  },
  {
    id: 'LM-PC-008',
    field: 'countryOfOrigin',
    name: 'Country of Origin',
    description: 'Country of origin must be declared for imported products.',
    reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 — Rule 6(1)(ea)',
    checkType: 'presence',
    severity: 'medium',
    applicableTo: ['all'],
    isActive: true,
  },
  {
    id: 'LM-PC-009',
    field: 'batchNumber',
    name: 'Batch / Lot Number',
    description: 'Batch, code, or lot number identifying manufacturing run must be declared.',
    reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 — Rule 6(1)(f)',
    checkType: 'presence',
    severity: 'medium',
    applicableTo: ['all'],
    isActive: true,
  },
  {
    id: 'LM-PC-010',
    field: 'fssaiLicense',
    name: 'FSSAI License Number',
    description: 'Food Safety and Standards Authority 14-digit license number must be present on food packaging.',
    reference: 'FSSAI Packaging Regulations, 2018 — Section 2.2',
    checkType: 'presence',
    severity: 'high',
    applicableTo: ['Food & Beverages', 'food'],
    isActive: true,
  },
];
