import type { Rule } from '../../types';

export const DEFAULT_RULES: Rule[] = [
  {
    id: 'LM-PC-001',
    field: 'manufacturer',
    name: 'Manufacturer / Packer Details',
    description: 'Name and complete address of the manufacturer, packer, or importer must be declared on every package.',
    reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 — Rule 6(1)(a)',
    checkType: 'presence',
    severity: 'high',
    applicableTo: ['all'],
    isActive: true,
  },
  {
    id: 'LM-PC-002',
    field: 'genericName',
    name: 'Common / Generic Name of Commodity',
    description: 'Common or generic name of the commodity contained in the package must be clearly stated.',
    reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 — Rule 6(1)(b)',
    checkType: 'presence',
    severity: 'high',
    applicableTo: ['all'],
    isActive: true,
  },
  {
    id: 'LM-PC-003',
    field: 'netQuantity',
    name: 'Net Quantity Declaration',
    description: 'Net quantity in standard units of weight, measure, or number (g, kg, ml, l, units) must be stated.',
    reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 — Rule 6(1)(c) & Rule 11',
    checkType: 'presence',
    severity: 'high',
    applicableTo: ['all'],
    isActive: true,
  },
  {
    id: 'LM-PC-004',
    field: 'mrp',
    name: 'Maximum Retail Price (MRP)',
    description: 'Maximum Retail Price inclusive of all taxes must be declared in Indian Rupees (₹ / Rs.).',
    reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 — Rule 6(1)(e)',
    checkType: 'presence',
    severity: 'high',
    applicableTo: ['all'],
    isActive: true,
  },
  {
    id: 'LM-PC-005',
    field: 'manufacturingDate',
    name: 'Date of Manufacture / Packing / Import',
    description: 'Month and year of manufacture, packing, or import must be declared on the principal display panel.',
    reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 — Rule 6(1)(d)',
    checkType: 'presence',
    severity: 'high',
    applicableTo: ['all'],
    isActive: true,
  },
  {
    id: 'LM-PC-006',
    field: 'bestBefore',
    name: 'Best Before / Use By / Expiry Date',
    description: 'Best before or use-by date declaration required for perishable or food commodities.',
    reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 — Rule 6(1)(d) & FSSAI 2.2',
    checkType: 'presence',
    severity: 'high',
    applicableTo: ['all'],
    isActive: true,
  },
  {
    id: 'LM-PC-007',
    field: 'consumerCare',
    name: 'Consumer Care / Helpline Details',
    description: 'Name, address, telephone number (toll-free/helpline), and email ID for consumer complaints must be declared.',
    reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 — Rule 6(1)(ac)',
    checkType: 'presence',
    severity: 'medium',
    applicableTo: ['all'],
    isActive: true,
  },
  {
    id: 'LM-PC-008',
    field: 'countryOfOrigin',
    name: 'Country of Origin',
    description: 'Country of origin must be stated for all imported packaged commodities.',
    reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 — Rule 6(1)(ea)',
    checkType: 'presence',
    severity: 'medium',
    applicableTo: ['all'],
    isActive: true,
  },
  {
    id: 'LM-PC-009',
    field: 'batchNumber',
    name: 'Batch / Lot / Code Number',
    description: 'Batch or lot number identifying the manufacturing run must be printed on the package.',
    reference: 'Legal Metrology (Packaged Commodities) Rules, 2011 — Rule 6(1)(f)',
    checkType: 'presence',
    severity: 'medium',
    applicableTo: ['all'],
    isActive: true,
  },
  {
    id: 'LM-PC-010',
    field: 'fssaiLicense',
    name: 'FSSAI License & Logo',
    description: '14-digit FSSAI license number and logo must be printed on all food and beverage packages.',
    reference: 'FSSAI (Packaging and Labelling) Regulations, 2018 & Legal Metrology Act Sec. 18',
    checkType: 'presence',
    severity: 'high',
    applicableTo: ['Food & Beverages', 'food'],
    isActive: true,
  },
];
